### ISSUE TITLE
Support for python-diskcache

### ISSUE THREAD

**Issue by silentjay** [BertrandBordage/django-cachalot#100] opened 2018-01-25 10:32 UTC
Receive the warning:
```
?: (cachalot.W001) Cache backend 'diskcache.DjangoCache' is not supported by django-cachalot.
	HINT: Switch to a supported cache backend like Redis or Memcached.
```
Are there any plans or workarounds to implement support?

https://github.com/grantjenks/python-diskcache

**Comment by BertrandBordage** [comment] 2018-01-26 10:34
Duplicate of #57.

**Closed by BertrandBordage** 2018-01-26 10:34 UTC
