### ISSUE TITLE
Django 1.8 support

### ISSUE THREAD

**Issue by maryokhin** [BertrandBordage/django-cachalot#27] opened 2015-08-05 10:11 UTC
Just wanted to bring some clarity whether `django-cachalot` in it's current state supports Django 1.8 or not. I tried running the package on Django 1.8, and while it's not crashing anything, I see that `django1.8` branch hasn't been merged to master and is failing the [build](https://travis-ci.org/BertrandBordage/django-cachalot/builds/58034259). So maybe some update for the community about this would be good from you. Thanks.

**Comment by BertrandBordage** [comment] 2015-08-06 10:32
Hello @maryokhin,

Currently, Django 1.8 is not officially supported by django-cachalot, because I still need to write some tests for the new ORM features introduced by it: UUIDField, DurationField, PostgreSQL specific fields, and a lot of refactoring in the ORM.

django-cachalot 1.1 will introduce Django 1.8 support while dropping 1.6 support.

However, django-cachalot is working with Django 1.8. It shows a few warnings (resolved in the django-1.8 branch that’ll become 1.1) and may not work perfectly with the new features listed above (even though I think they should work fine), but apart from that it works.

**So it’s not 100% safe now for Django 1.8, but if invalidation issues are not critical to you, you can very well use it now.** But if you notice any weird behavior, reporting the bug would be very helpful!

Now when will 1.1 be out? In a near future. I honestly don’t use Django 1.8 in production yet, mainly because heavy dependencies I use weren’t Django 1.8 compatible until this summer (21 days ago for [Wagtail](https://github.com/torchbox/wagtail) and 40 days ago for [django CMS](https://github.com/divio/django-cms)) and because I don’t have as much time for open source as I would like. I’ll probably release 1.1 in September, when I’ll update all my projects to Django 1.8.

Better late than broken :p

**Comment by maryokhin** [comment] 2015-08-06 11:40
Great, thanks for the comprehensive write-out on how things are going, @BertrandBordage!

**Comment by olifante** [comment] 2015-08-06 13:54
django-cms has supported django 1.8 for more than a month now:
http://django-cms.readthedocs.org/en/3.1.2/how_to/install.html
http://www.django-cms.org/en/blog/2015/07/03/312-release/

**Comment by alsonkemp** [comment] 2015-09-03 18:02
+1 for this.

    So it’s not 100% safe now for Django 1.8, but if
    invalidation issues are not critical to you, you can very well use it now.

We're seeing occasional, invalidation issues: save a model in Django Admin; the DB representation changes; about 50% of the time, the Admin representation does not reflect changes.

**Comment by BertrandBordage** [comment] 2015-09-04 20:15
@alsonkemp What is the representation using? Is that a simple thing like:
```python
def __str__(self):
    return self.name
```
or something more complex? Does these representations rely on related objects or on a new queryset?

**Comment by marccerrato** [comment] 2015-09-08 15:23
+1

We're having occasional invalidation issues as well. Also the invalid result show about 50% of the time. Even using the Django shell command.

**Comment by alsonkemp** [comment] 2015-09-08 22:01
@BertrandBordage Many of our __str__ (technically, __unicode__) implementations use related objects.  We use Admin a lot, so having nice, detailed string reps is nice.  e.g.:

        def __unicode__(self):
        return u"[#%s] %s [%s]" % (self.id, self.site._short(), self.coordinates())

We can see the object's id, the site it's in and the coordinates within the site.  Would this harm invalidation?

**Comment by davidrideout** [comment] 2015-09-08 22:05
+1

**Comment by atungare** [comment] 2015-09-09 17:07
+1

**Comment by brunocoelho** [comment] 2015-09-09 17:09
+1

**Comment by gilcarmel** [comment] 2015-09-09 17:09
+1

**Comment by rishikesh-singh** [comment] 2015-09-09 17:18
+1

**Comment by jasuca** [comment] 2015-09-09 17:20
+1

**Comment by alsonkemp** [comment] 2015-09-09 17:22
Wow, django-cachalot has some serious love.  I'm happy to help debug this issue, but I'm not quite sure where to begin. Pointers?

**Comment by xino12** [comment] 2015-09-09 17:30
+1

**Comment by BertrandBordage** [comment] 2015-09-09 18:52
@alsonkemp No, it should not mess with the invalidation, everything should work as if django-cachalot wasn’t there (except that it’s faster).

I will issue version 1.1, the first Django 1.8 compatible release, by the end of the month. Sorry about all this delay, but I have a company to run and it leaves me less time to code than I would like :(

**Comment by BertrandBordage** [comment] 2015-10-02 17:35
It’s a bit late, I know, but for your information I’m on it :)

**Comment by brunocoelho** [comment] 2015-10-02 18:49
:+1:

**Comment by BertrandBordage** [comment] 2015-10-04 21:35
Hi everyone (especially @alsonkemp & @marccerrato),

I worked a lot on this this issue this week-end! These issues especially took me lots of hours:
- Finding the cleanest way possible to test PostgreSQL-only models while having other DB engines ignore its migrations and tests
- django.contrib.postgres doesn’t always prepare data for psycopg2, I had to be extremely careful with which parameter types were passed to psycopg2
- [This new Django bug](https://code.djangoproject.com/ticket/25501)

We’re close to release 1.1, I will just have to create the new features in #18 and #29 before.

However, something bothers me: I could never reproduce the invalidation issue @alsonkemp & @marccerrato faced. Could you please send me privately a model where the issue occurred, your Django settings file(s) (without sensitive data)? Also: maybe you saw a consequence of [using django-cachalot on multiple servers](http://django-cachalot.readthedocs.org/en/latest/limits.html#multiple-servers)?

**Comment by erwinfeser** [comment] 2015-10-06 12:34
+1

**Comment by marccerrato** [comment] 2015-10-09 16:11
@BertrandBordage Sorry for my late reply.

We also had the invalidation issue when using an environment with just one server, and  we have spotted the problem with different models.

I can't share any of that code for confidentiality, though. But I'd be pleased to answer any questions about it you might have.

**Comment by BertrandBordage** [comment] 2015-10-10 16:57
@alsonkemp Could you send me the problematic model and your settings file(s)?

@marccerrato No problem if you can’t share private code. Could you therefore create a minimal example? Or at least the version numbers you’re using for:
- django-cachalot
- Django
- the cache backend (python-memcached, pylibmc, django-redis (and not django-redis-cache), locmem or filebased)
- the cache software (memcached or redis)
- the OS

If none of you can provide me more information, I will have to consider your problem as invalid and coming from you, not from cachalot. I spent hours on trying to reproduce your problem, and at no moment it happened to me. I tried on extremely complex methods I have on one of my project (one of them calling more than 500 lines of code, using fks, 1to1, m2m, generic fks, raw SQL and complex querysets). No way to reproduce the problem with Django 1.8 and django-cachalot 1.0.3.

**Comment by luisehk** [comment] 2015-10-14 16:33
+1

**Comment by marccerrato** [comment] 2015-10-14 16:49
@BertrandBordage
- Packages versions:
  - Django==1.8.4
  - django-cachalot==1.0.3
  - django-redis==4.0.0
  - redis==2.10.3
- Cache: Redis 2.8.8
- OS: CentOS7

**Comment by BertrandBordage** [comment] 2015-10-14 23:20
@marccerrato:
I’m using really similar versions (the only real difference is the system, I tested using Ubuntu 14.04, 14.10 & 15.04).
Can you see this issue on two machines (like your dev machine + the prod machine)?

I’m sure that the test suite covers all the possible scenario given what you describe, so running it should help finding more info:
- If you don’t use a custom user model, the whole cachalot test suite should work on your project.
Please run `./manage.py test cachalot` in your project, some test may be skipped but none should cause an error. If errors occur, please paste them here.
- If you use a custom user model, clone the repo (`git clone https://github.com/BertrandBordage/django-cachalot`), then configure the test settings in the root `settings.py` (remove all db & cache backends except default ones & configure them), create the db table if needed, and run the tests using `./manage.py test cachalot`. If errors occur, paste them here.

Thanks!

**Comment by marccerrato** [comment] 2015-10-15 14:33
@BertrandBordage Yes, we noticed the issue in two different machines (demo and prod), but both have same OS and software versions.

We don't use a custom user model, but we had to adapt some of our settings to make it possible to run the cachalot tests. We tried with version 1.0.3 and last commit from branch django-1.8, and with LocMemCache and Redis and we found some failures/errors: https://gist.github.com/marccerrato/27439ff66132fed05808

I hope it can help you.

**Comment by BertrandBordage** [comment] 2015-10-15 15:18
@marccerrato Excellent! Thanks a lot, it’ll be really helpful. I’ll work on it after work, in a few hours.

**Comment by BertrandBordage** [comment] 2015-10-16 00:19
@marccerrato:
A few errors are expected with django-cachalot 1.0.3, but none should happen with the django-1.8 branch.
Most of the errors you see are caused by configuration differences between my test settings and your project settings. If you add `'django.contrib.postgres',` to `INSTALLED_APPS` and set `USE_TZ = False`, these errors should disappear:
```ProgrammingError: can't adapt type 'dict'```
```TypeError: can't compare offset-naive and offset-aware datetimes```

However, it leaves a few assertion errors only with the locmem cache, and not with redis:
```FAIL: test_invalidate_cachalot_multi_cache (cachalot.tests.api.CommandTestCase)```
```FAIL: test_having (cachalot.tests.read.ReadTestCase)```
```FAIL: test_cache (cachalot.tests.settings.SettingsTestCase)```

All these failing tests have a wrong number of query executed: the first two execute an unnecessary query, and the last one uses a stale cached result instead of executing a query. The first and third tests are about switching from one cache to another, and the second one tests a quite rare ORM query that’s the only one that can lead to `HAVING` SQL clauses. It’s very unlikely that you’re problem is related to `HAVING` clauses, so something may be wrong with your multiple cache setup.

Could you privately send me only your cache settings if that’s possible?

We’ll catch and squash that bug!

**Comment by marccerrato** [comment] 2015-10-16 11:03
Hey @BertrandBordage:
We ran the tests again with `'django.contrib.postgres'` in  `INSTALLED_APPS` and `USE_TZ = False`:
- With `branch-1.8` and Redis:  
Everything's OK.  
Using this cache config:  
```python
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "127.0.0.1:6379:1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
    "sessions": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "127.0.0.1:6379:3",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
}
```
- With `branch-1.8 and locmem cache`:  
`FAIL: test_invalidate_cachalot_multi_cache (cachalot.tests.api.CommandTestCase)`  
`FAIL: test_cache (cachalot.tests.settings.SettingsTestCase)`  
Using this cache config:
```python
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    },
    'sessions': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    },
}
```

So, as the issue was noticed with `django-cachalot==1.0.3` and `Django==1.8.4`, perhaps it was something you have already fixed on the branch `django-1.8`? Test `test_filter (cachalot.tests.read.ReadTestCase)` was failing when filtering with dates or datetimes.

**Comment by BertrandBordage** [comment] 2015-10-16 12:09
Ah, that’s because you’re using twice the same cache in your locmem configuration. In the multi-cache tests, I verify that caching is independent between the caches. Of course, if the two caches are the same, the test fails…

So if you set it to something like this, the two failing tests should pass:
```python
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'first-cache-id',
    },
    'sessions': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'second-cache-id',
    },
}
```

The failing `test_filter` test is because Django 1.8 now directly passes a datetime to psycopg2 instead of a string, which was not expected in django-cachalot 1.0.3, and therefore not cached. So this can in no way be the cause of your problem.

So either the problem is coming from something in your application but not in your settings, either django-cachalot doesn’t test something properly. I’ll review again the whole test suite this week-end, but I’m nearly sure it’s not coming from it.

**Comment by alsonkemp** [comment] 2015-10-16 18:48
@BertrandBordage for some reason, NTP was not working on our API servers and they had drifted by 2-3 minutes.  Unfortunately, we did not really catch this:

    If you deploy the same Django project on multiple machines, but with a
    centralized cache server, all the machines serving Django need to have
    their clocks as synchronize as possible. Otherwise, invalidations will
    happen with a latency from one server to another. A difference of even a few
    seconds can be harmful, so double check this!

Would be good to add a screaming callout to the Quickstart about this.  I'll send you a PR.

**Comment by BertrandBordage** [comment] 2015-10-16 20:14
@alsonkemp Ah, cool! Glad you found the cause. I discussed about that clock issue on your pull request, #31.

**Comment by BertrandBordage** [comment] 2015-10-24 23:03
Django-cachalot 1.1 is almost there!
All the features I wanted to add for this release are there, added most of the documentation I had to do, and I still need to write a few tests just-to-be-sure.

Still no sign of the issue @marccerrato reported. I’ll finish that new release tomorrow, it’ll be 1.1.0 (no time for a release candidate, there has been enough wait). If some face the issue @marccerrato reported, I’ll fix it in a 1.1.1 release. But sincerely, I can’t find any explanation. I learned a lot on the internals of memcached and Redis before creating django-cachalot, read carefully the whole cache source in Django (including backends).

There’s zero mystery to me in the whole django-cachalot workflow, and the only explanations I can come up with is that you have desynchronised clocks or you run scripts outside Django asynchronously without calling `invalidate_cachalot` (or using `CACHALOT_UNCACHABLE_TABLES`).

**Comment by johntellsall** [comment] 2015-10-26 19:05
thanks for your work Bertrand!

**Comment by marccerrato** [comment] 2015-10-26 19:37
Thank you @BertrandBordage. We will give it a try with the new version and see if we notice the issue again.

**Comment by BertrandBordage** [comment] 2015-10-26 19:45
Didn’t issue release 1.1.0 yesterday unfortunately. While writing docs, I decided to create a comparison with django-cache-machine and django-cacheops, but in the end it took me most of the day… You can see it here: https://github.com/BertrandBordage/django-cachalot/blob/django-1.8/docs/introduction.rst#comparison-with-similar-tools

**Comment by BertrandBordage** [comment] 2015-10-28 19:15
Django-cachalot 1.1.0 is out, fixing this issue!
There has been a few changes, please [read the whole changelog](http://django-cachalot.readthedocs.org/en/latest/changelog.html#id1).

**Closed by BertrandBordage** 2015-10-28 19:15 UTC
Labels: enhancement

**Comment by xino12** [comment] 2015-12-09 17:36
Hi @BertrandBordage we( @marccerrato, @jcugat and me) have just have found why the 50% result issue.

We have found that if we use a Master - Slave setup with postgres with different DB_ALIAS for the same SQL the same hash is generated in the function get_table_cache_key.

And when a write is done only the hash that matches with the DB_ALIAS that received the write is invalidated.

We use this app for multidb support. https://github.com/jbalogh/django-multidb-router

I don't know if you planned this case but it would be awesome if cachalot could work with Master-Slave support.

It might be a good idea when invalidating a model to iterate through all Routers and check which ones can read the model and then invalidate the hashes for each database alias.
I hope this is helpful.  

Thanks.

**Comment by BertrandBordage** [comment] 2015-12-18 10:58
@xino12 As I wrote in #37, using multiple database aliases and a router causes no problem: cachalot handles that. What you wrote about the hashes is wrong: both SQL query and table cache keys contain the database alias, so you have a different hash for each database.

The only problem is that **the replica database is updated outside Django**. Read #37 for more detail.
