### ISSUE TITLE
Django 1.9 error

### ISSUE THREAD

**Issue by puterleat** [BertrandBordage/django-cachalot#41] opened 2015-12-17 23:13 UTC
I realise django 1.8 is only just supported, but wanted to give you a heads up on this error one gets when running cachalot 1.1 with django 1.9:

      Traceback (most recent call last):
        File "./manage.py", line 12, in <module>
          execute_from_command_line(sys.argv)
        File "/Users/foo/envs/sbox3000/lib/python3.4/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
          utility.execute()
        File "/Users/foo/envs/sbox3000/lib/python3.4/site-packages/django/core/management/__init__.py", line 342, in execute
          self.fetch_command(subcommand).run_from_argv(self.argv)
        File "/Users/foo/envs/sbox3000/lib/python3.4/site-packages/django/core/management/base.py", line 348, in run_from_argv
          self.execute(*args, **cmd_options)
        File "/Users/foo/envs/sbox3000/lib/python3.4/site-packages/django/core/management/base.py", line 399, in execute
          output = self.handle(*args, **options)
        File "/Users/foo/envs/sbox3000/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 83, in handle
          verbosity=self.verbosity,
        File "/Users/foo/envs/sbox3000/lib/python3.4/site-packages/django/core/management/__init__.py", line 119, in call_command
          return command.execute(*args, **defaults)
        File "/Users/foo/envs/sbox3000/lib/python3.4/site-packages/django/core/management/base.py", line 399, in execute
          output = self.handle(*args, **options)
        File "/Users/foo/envs/sbox3000/lib/python3.4/site-packages/django/core/management/commands/showmigrations.py", line 36, in handle
          return self.show_list(connection, options['app_labels'])
        File "/Users/foo/envs/sbox3000/lib/python3.4/site-packages/django/core/management/commands/showmigrations.py", line 44, in show_list
          loader = MigrationLoader(connection, ignore_no_migrations=True)
        File "/Users/foo/envs/sbox3000/lib/python3.4/site-packages/django/db/migrations/loader.py", line 49, in __init__
          self.build_graph()
        File "/Users/foo/envs/sbox3000/lib/python3.4/site-packages/django/db/migrations/loader.py", line 176, in build_graph
          self.applied_migrations = recorder.applied_migrations()
        File "/Users/foo/envs/sbox3000/lib/python3.4/site-packages/django/db/migrations/recorder.py", line 66, in applied_migrations
          return set(tuple(x) for x in self.migration_qs.values_list("app", "name"))
        File "/Users/foo/envs/sbox3000/lib/python3.4/site-packages/django/db/models/query.py", line 258, in __iter__
          self._fetch_all()
        File "/Users/foo/envs/sbox3000/lib/python3.4/site-packages/django/db/models/query.py", line 1074, in _fetch_all
          self._result_cache = list(self.iterator())
        File "/Users/foo/envs/sbox3000/lib/python3.4/site-packages/django/db/models/query.py", line 128, in __iter__
          for row in compiler.results_iter():
        File "/Users/foo/envs/sbox3000/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 806, in results_iter
          results = self.execute_sql(MULTI)
        File "/Users/foo/envs/sbox3000/lib/python3.4/site-packages/cachalot/monkey_patch.py", line 29, in inner
          out = original(compiler, *args, **kwargs)
        File "/Users/foo/envs/sbox3000/lib/python3.4/site-packages/cachalot/monkey_patch.py", line 77, in inner
          table_cache_keys = _get_table_cache_keys(compiler)
        File "/Users/foo/envs/sbox3000/lib/python3.4/site-packages/cachalot/utils.py", line 147, in _get_table_cache_keys
          tables = _get_tables(compiler.query, db_alias)
        File "/Users/foo/envs/sbox3000/lib/python3.4/site-packages/cachalot/utils.py", line 128, in _get_tables
          + query.having.children)
      AttributeError: 'Query' object has no attribute 'having'

**Comment by BertrandBordage** [comment] 2015-12-18 11:09
Thanks @puterleat, that’s caused by django/django@afe0bb7b13bb8dc4370f32225238012c873b0ee3, it’ll be fixed in the next release of django-cachalot, version 1.2.0.

**Comment by BertrandBordage** [comment] 2015-12-18 16:16
Fixed by 885d68b0089fb17976c8100e1a6a608993040ff0 and 2ffe564e3ead5809e4392ec93bfdb4083df7d28a.

**Closed by BertrandBordage** 2015-12-18 16:16 UTC
Labels: enhancement
